### ISSUE TITLE
Verbs being changed

### ISSUE THREAD

**Issue by comatosebunny** [max-kamps/jpdb-browser-reader#7] opened 2023-03-07 20:10 UTC
I'm only noticing this with verbs, but they'll often get deconjugated. ございません becomes ござる, なった becoming なる. This only happens in ttu so far with the extension, the text itself shows up normally in any other reader without the extension. It doesn't happen with all verbs, but enough that it became noticeable.

**Comment by max-kamps** [comment] 2023-03-07 20:42
This bug is caused by the current fallback logic for words with no furigana.
The code assumes that using the word's spelling instead is fine. However, the spelling as reported through the jpdb API does not include any conjugations.

This will be fixed along with #8. Rather than waiting for the furigana customization settings as originally planned, I will prioritize just fixing these bugs for now.

**Closed** 2023-03-11 12:09 UTC
Labels: bug, critical
